resources:
  requests:
    cpu: ${{values.resources_requests_cpu}}m
    memory: ${{values.resources_requests_memory}}Mi
  limits:
    cpu: ${{values.resources_limit_cpu}}m
    memory: ${{values.resources_limit_memory}}Mi    
hpa:
  enabled: ${{values.hpaEnabled}}
  {%- if values.hpaEnabled == true %}
  minReplicas: ${{values.hpaMinReplicas}}
  maxReplicas: ${{values.HPAmaxReplicas}}
  targetCPUUtilizationPercentage: ${{values.hpaTargetCPUUtilizationPercentage}}
  {%- if values.hpaMetrics |length > 0 %}
  metrics: 
  {%- for value in values.hpaMetrics  %}
  - ${{ value }}
  {%- endfor %}
  {%- else %}
  metrics: []
  {%- endif %}
  {%- endif %}
image:
  repository: ${{values.ImageRepository}}/${{values.ImageName}}
  tag: ${{values.ImageTag}}
{% if values.Environment  | length > 0 -%}
env:
{%- for kv in values.Environment  %}
  ${{ kv.Key }}: ${{ kv.Value }}
{%- endfor %}
{% endif -%}


ingress:
  enabled: ${{values.IngressEnabled}}
  {%- if values.IngressEnabled == true %}
  ingressClassName: ${{values.IngressClassName}}
  {% if values.IngressAnnotations  | length > 0 -%}
  annotations:
    {%- for kv in values.IngressAnnotations  %}
    ${{ kv.Key }}: ${{ kv.Value }}
    {%- endfor %}
  {% endif -%}
  labels: {}
  path: ${{values.IngressPath}}
  {% if values.IngressHost  | length > 0 -%}
  hosts:
    {%- for host in values.IngressHost  %}
    - ${{ host }}
    {%- endfor %}
  {% endif -%}
  {%- if values.IngressTLSEnabled == true %}
  tls:
  {%- for i in IngressTLS  %}
  - secretName: ${{i.IngressSecretName}}
    hosts:
    {%- for j in i.IngressHostTLS  %}
    - ${{j}}
    {%- endfor %}
  {%- endfor %}
  {%- endif %}
  {%- endif %}