resources:
  requests:
    cpu: ${{values.requests_cpu}}
    memory: ${{values.requests_memory}}
  limits:
    cpu: 500m
    memory: 1024Mi

hpa:
  enabled: ${{values.enabledHPA}}
  minReplicas: ${{values.minReplicasHPA}}
  maxReplicas: ${{values.maxReplicasHPA}}
  targetCPUUtilizationPercentage: ${{values.targetCPUUtilizationPercentageHPA}}
  {%- if values.metricsHPA |length > 1 %}
  metrics: 
    {%- for value in values.metricsHPA  %}
    - {{ value }}
    {%- endfor %}
  {%- else %}
  metrics: []
  {%- endif %}
 