resources:
  requests:
    cpu: ${{values.resources_requests_cpu}}m
    memory: ${{values.resources_requests_memory}}Mi
  limits:
    cpu: ${{values.resources_limit_cpu}}m
    memory: ${{values.resources_limit_memory}}Mi    
hpa:
  enabled: ${{values.hpaEnabled}}
  minReplicas: ${{values.hpaMinReplicas}}
  maxReplicas: ${{values.HPAmaxReplicas}}
  targetCPUUtilizationPercentage: ${{values.hpaTargetCPUUtilizationPercentage}}
  {%- if values.hpaMetrics |length > 0 %}
  metrics: 
  {%- for value in values.hpaMetrics  %}
  - ${{ value }}
  {%- endfor %}
  {%- else %}
  metrics: []
  {%- endif %}
{% if values.Environment  | length > 0 -%}
env:
{%- for kv in values.Environment  %}
  ${{ kv.Key }}: ${{ kv.Value }}
{%- endfor %}
{% endif -%}