apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: deployment-template
  title: Generate Deployment Repository
  description: Create a simple deployment application
  tags:
    - deployment
    - gitops
spec:
  owner: my-org-idp
  type: service

  parameters:
    - title: Provide Information for Application
      required:
        - application_id
      properties:
        application_id:
          title: Name
          type: string
          description: Unique name of the deployment application
          ui:autofocus: true
        description:
          title: Description
          type: string
          description: Help others understand what this deployment repo is for.
        owner:
          title: Owner
          type: string
          description: IdP owner of the component
          ui:field: OwnerPicker
          ui:options:
            allowedKinds:
              - Group
    - title: Fill in Resources Application
      required:
        - requests_cpu
        - requests_memory
      properties:
        requests_cpu:
          title: Request CPU
          type: string
        requests_memory:
          title: Request Memory
          type: string
          
    - title: Application repository Information
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com

  steps:
    - id: template
      name: Generating component
      action: fetch:template
      input:
        url: ./skeleton
        values:
          application_id: ${{ parameters.application_id }}
          description: ${{ parameters.description }}

    - id: publish
      name: Publishing to Source Code Repository
      action: publish:github
      input:
        description: This is ${{ parameters.application_id }}
        repoUrl: ${{ parameters.repoUrl }}
        defaultBranch: main
        repoVisibility: public

    - id: register
      name: Registering to the Catalog
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info.yaml'

  output:
    links:
      - title: Source Code Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Open Component in catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}